apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: casestudy-admin-ui
    visualize: "true"
    uses: redis
  name: casestudy-admin-ui
spec:
  replicas: 1
  selector:
    run: casestudy-admin-ui
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: casestudy-admin-ui
        visualize: "true"
        uses: redis
    spec:
      containers:
      - image: rpicloud/casestudy-admin-ui
        name: casestudy-admin-ui
        resources: {}
status:
  replicas: 0
