apiVersion: v1
kind: Service
metadata:
  labels:
    run: casestudy-config-service
    visualize: "true"
  name: casestudy-config-service
spec:
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 8888
    protocol: TCP
    targetPort: 8080
  selector:
    run: casestudy-config-service
status:
  loadBalancer: {}
