apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: casestudy-config-service
    visualize: "true"
  name: casestudy-config-service
spec:
  replicas: 1
  selector:
    app: casestudy-config-service
  template:
    metadata:
      labels:
        app: casestudy-config-service
        visualize: "true"
    spec:
      containers:
      - image: rpicloud/casestudy-config-service
        name: casestudy-config-service
        imagePullPolicy: Always
        resources: {}
        ports:
        - containerPort: 6379
status:
  replicas: 0
