apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: casestudy-config-service
    visualize: "true"
  name: casestudy-config-service
spec:
  replicas: 1
  selector:
    run: casestudy-config-service
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: casestudy-config-service
        visualize: "true"
    spec:
      containers:
      - image: rpicloud/casestudy-config-service
        name: casestudy-config-service
        resources: {}
status:
  replicas: 0
