apiVersion: v1
kind: Service
metadata:
  labels:
    run: casestudy-ui
    visualize: "true"
  name: casestudy-ui
spec:
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    run: casestudy-ui
status:
  loadBalancer: {}