apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: casestudy-test-resource
    visualize: "true"
    uses: redis
  name: casestudy-test-resource
spec:
  replicas: 1
  selector:
    run: casestudy-test-resource
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: casestudy-test-resource
        visualize: "true"
        uses: redis
    spec:
      containers:
      - image: rpicloud/casestudy-test-resource
        name: casestudy-test-resource
        imagePullPolicy: Always
        resources: {}
status:
  replicas: 0
