apiVersion: v1
kind: Service
metadata:
  labels:
    run: casestudy-gateway
    visualize: "true"
  name: casestudy-gateway
spec:
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: casestudy-gateway
status:
  loadBalancer: {}