apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    role: master
    visualize: "true"
spec:
  containers:
    - name: redis-master
      image: hypriot/rpi-redis
      ports:
      - name: redis-server  
        containerPort: 6379
