apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    app: redis
    visualize: "true"
spec:
  containers:
    - name: redis
      image: hypriot/rpi-redis
      ports:
      - containerPort: 6379
