apiVersion: v1
kind: ReplicationController
metadata:
  creationTimestamp: null
  labels:
    run: redis
    visualize: "true"
  name: redis
spec:
  replicas: 1
  selector:
    run: redis
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: redis
        visualize: "true"
    spec:
      containers:
      - image: hypriot/rpi-redis
        name: redis
        resources: {}
status:
  replicas: 0
