apiVersion: v1
kind: Service
metadata:
  #  creationTimestamp: null
  labels:
    app: redis
    role: master
    visualize: "true"
  name: redis
spec:
  #deprecatedPublicIPs:
  #- 192.168.1.11
  externalIPs:
  - 192.168.1.11
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
    role: master
    visualize: "true"
status:
  loadBalancer: {}
