apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: redis
    role: master
    visualize: "true"
  name: redis
spec:
  replicas: 1
  selector:
    app: redis
    role: master
    visualize: "true"
  template:
    metadata:
      labels:
        app: redis
        role: master
        visualize: "true"
    spec:
      containers:
      - image: hypriot/rpi-redis
        name: redis
        ports:
        - containerPort: 6379
        resources: {}

# apiVersion: v1
# kind: ReplicationController
# metadata:
#   creationTimestamp: 2016-02-24T11:56:28Z
#   generation: 1
#   labels:
#     app: redis
#     run: redis
#     visualize: "true"
#   name: redis
#   namespace: default
#   resourceVersion: "28054"
#   selfLink: /api/v1/namespaces/default/replicationcontrollers/redis
#   uid: a347b86a-daed-11e5-a160-b827ebf9c324
# spec:
#   replicas: 1
#   selector:
#     app: redis
#     run: redis
#     visualize: "true"
#   template:
#     metadata:
#       creationTimestamp: null
#       labels:
#         app: redis
#         run: redis
#         visualize: "true"
#     spec:
#       containers:
#       - image: hypriot/rpi-redis
#         imagePullPolicy: IfNotPresent
#         name: redis
#         resources: {}
#         terminationMessagePath: /dev/termination-log
#       dnsPolicy: ClusterFirst
#       restartPolicy: Always
#       terminationGracePeriodSeconds: 30
# status:
#   replicas: 0